# Generated by Django 4.2.26 on 2025-12-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_file_file_size_file_file_type_like_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
